services:
  mysql:
    image: 'mysql:lts'
    environment:
      - 'MYSQL_ROOT_PASSWORD=rootpass'
      - 'MYSQL_DATABASE=univer_db'
      - 'MYSQL_USER=univer_db_user'
      - 'MYSQL_PASSWORD=pass'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - '3306:3306'

  envoy:
    image: envoyproxy/envoy:latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"  # HTTP listener
