spring:
  application:
    name: univer-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/univer_db
    username: univer_db_user
    password: pass
#  flyway:
#    locations: classpath:db/migration:

grpc:
  server:
    port: 9090